using csharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace GildedRose
{
    public class GildedRoseBlackBoxTests
    {
        [Theory]
        [MemberData(nameof(TestCases))]
        public void BlackBoxTests(Item original, Item expected)
        {
            var g = new csharp.GildedRose(new List<Item> { original });
            g.UpdateQuality();
            var updated = g.Items[0];
            Assert.Equal(expected.Name, updated.Name);
            Assert.Equal(expected.SellIn, updated.SellIn);
            Assert.Equal(expected.Quality, updated.Quality);
        }

        public static IEnumerable<object[]> TestCases()
        {
            return new object[][] 
            {
                new object[] { new Item{ Name="Anyname", SellIn=-1, Quality=-1},new Item { Name = "Anyname", SellIn = -2, Quality = -1 }},
                new object[] { new Item { Name = "Anyname", SellIn = -1, Quality = 0 }, new Item { Name = "Anyname", SellIn = -2, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = -1, Quality = 1 }, new Item { Name = "Anyname", SellIn = -2, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = -1, Quality = 49 }, new Item { Name = "Anyname", SellIn = -2, Quality = 47 } },
                new object[] { new Item { Name = "Anyname", SellIn = -1, Quality = 50 }, new Item { Name = "Anyname", SellIn = -2, Quality = 48 } },
                new object[] { new Item { Name = "Anyname", SellIn = -1, Quality = 51 }, new Item { Name = "Anyname", SellIn = -2, Quality = 49 } },
                new object[] { new Item { Name = "Anyname", SellIn = 0, Quality = -1 }, new Item { Name = "Anyname", SellIn = -1, Quality = -1 } },
                new object[] { new Item { Name = "Anyname", SellIn = 0, Quality = 0 }, new Item { Name = "Anyname", SellIn = -1, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 0, Quality = 1 }, new Item { Name = "Anyname", SellIn = -1, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 0, Quality = 49 }, new Item { Name = "Anyname", SellIn = -1, Quality = 47 } },
                new object[] { new Item { Name = "Anyname", SellIn = 0, Quality = 50 }, new Item { Name = "Anyname", SellIn = -1, Quality = 48 } },
                new object[] { new Item { Name = "Anyname", SellIn = 0, Quality = 51 }, new Item { Name = "Anyname", SellIn = -1, Quality = 49 } },
                new object[] { new Item { Name = "Anyname", SellIn = 1, Quality = -1 }, new Item { Name = "Anyname", SellIn = 0, Quality = -1 } },
                new object[] { new Item { Name = "Anyname", SellIn = 1, Quality = 0 }, new Item { Name = "Anyname", SellIn = 0, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 1, Quality = 1 }, new Item { Name = "Anyname", SellIn = 0, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 1, Quality = 49 }, new Item { Name = "Anyname", SellIn = 0, Quality = 48 } },
                new object[] { new Item { Name = "Anyname", SellIn = 1, Quality = 50 }, new Item { Name = "Anyname", SellIn = 0, Quality = 49 } },
                new object[] { new Item { Name = "Anyname", SellIn = 1, Quality = 51 }, new Item { Name = "Anyname", SellIn = 0, Quality = 50 } },
                new object[] { new Item { Name = "Anyname", SellIn = 5, Quality = -1 }, new Item { Name = "Anyname", SellIn = 4, Quality = -1 } },
                new object[] { new Item { Name = "Anyname", SellIn = 5, Quality = 0 }, new Item { Name = "Anyname", SellIn = 4, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 5, Quality = 1 }, new Item { Name = "Anyname", SellIn = 4, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 5, Quality = 49 }, new Item { Name = "Anyname", SellIn = 4, Quality = 48 } },
                new object[] { new Item { Name = "Anyname", SellIn = 5, Quality = 50 }, new Item { Name = "Anyname", SellIn = 4, Quality = 49 } },
                new object[] { new Item { Name = "Anyname", SellIn = 5, Quality = 51 }, new Item { Name = "Anyname", SellIn = 4, Quality = 50 } },
                new object[] { new Item { Name = "Anyname", SellIn = 6, Quality = -1 }, new Item { Name = "Anyname", SellIn = 5, Quality = -1 } },
                new object[] { new Item { Name = "Anyname", SellIn = 6, Quality = 0 }, new Item { Name = "Anyname", SellIn = 5, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 6, Quality = 1 }, new Item { Name = "Anyname", SellIn = 5, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 6, Quality = 49 }, new Item { Name = "Anyname", SellIn = 5, Quality = 48 } },
                new object[] { new Item { Name = "Anyname", SellIn = 6, Quality = 50 }, new Item { Name = "Anyname", SellIn = 5, Quality = 49 } },
                new object[] { new Item { Name = "Anyname", SellIn = 6, Quality = 51 }, new Item { Name = "Anyname", SellIn = 5, Quality = 50 } },
                new object[] { new Item { Name = "Anyname", SellIn = 7, Quality = -1 }, new Item { Name = "Anyname", SellIn = 6, Quality = -1 } },
                new object[] { new Item { Name = "Anyname", SellIn = 7, Quality = 0 }, new Item { Name = "Anyname", SellIn = 6, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 7, Quality = 1 }, new Item { Name = "Anyname", SellIn = 6, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 7, Quality = 49 }, new Item { Name = "Anyname", SellIn = 6, Quality = 48 } },
                new object[] { new Item { Name = "Anyname", SellIn = 7, Quality = 50 }, new Item { Name = "Anyname", SellIn = 6, Quality = 49 } },
                new object[] { new Item { Name = "Anyname", SellIn = 7, Quality = 51 }, new Item { Name = "Anyname", SellIn = 6, Quality = 50 } },
                new object[] { new Item { Name = "Anyname", SellIn = 10, Quality = -1 }, new Item { Name = "Anyname", SellIn = 9, Quality = -1 } },
                new object[] { new Item { Name = "Anyname", SellIn = 10, Quality = 0 }, new Item { Name = "Anyname", SellIn = 9, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 10, Quality = 1 }, new Item { Name = "Anyname", SellIn = 9, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 10, Quality = 49 }, new Item { Name = "Anyname", SellIn = 9, Quality = 48 } },
                new object[] { new Item { Name = "Anyname", SellIn = 10, Quality = 50 }, new Item { Name = "Anyname", SellIn = 9, Quality = 49 } },
                new object[] { new Item { Name = "Anyname", SellIn = 10, Quality = 51 }, new Item { Name = "Anyname", SellIn = 9, Quality = 50 } },
                new object[] { new Item { Name = "Anyname", SellIn = 11, Quality = -1 }, new Item { Name = "Anyname", SellIn = 10, Quality = -1 } },
                new object[] { new Item { Name = "Anyname", SellIn = 11, Quality = 0 }, new Item { Name = "Anyname", SellIn = 10, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 11, Quality = 1 }, new Item { Name = "Anyname", SellIn = 10, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 11, Quality = 49 }, new Item { Name = "Anyname", SellIn = 10, Quality = 48 } },
                new object[] { new Item { Name = "Anyname", SellIn = 11, Quality = 50 }, new Item { Name = "Anyname", SellIn = 10, Quality = 49 } },
                new object[] { new Item { Name = "Anyname", SellIn = 11, Quality = 51 }, new Item { Name = "Anyname", SellIn = 10, Quality = 50 } },
                new object[] { new Item { Name = "Anyname", SellIn = 12, Quality = -1 }, new Item { Name = "Anyname", SellIn = 11, Quality = -1 } },
                new object[] { new Item { Name = "Anyname", SellIn = 12, Quality = 0 }, new Item { Name = "Anyname", SellIn = 11, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 12, Quality = 1 }, new Item { Name = "Anyname", SellIn = 11, Quality = 0 } },
                new object[] { new Item { Name = "Anyname", SellIn = 12, Quality = 49 }, new Item { Name = "Anyname", SellIn = 11, Quality = 48 } },
                new object[] { new Item { Name = "Anyname", SellIn = 12, Quality = 50 }, new Item { Name = "Anyname", SellIn = 11, Quality = 49 } },
                new object[] { new Item { Name = "Anyname", SellIn = 12, Quality = 51 }, new Item { Name = "Anyname", SellIn = 11, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = -1, Quality = -1 }, new Item { Name = "Aged Brie", SellIn = -2, Quality = 1 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = -1, Quality = 0 }, new Item { Name = "Aged Brie", SellIn = -2, Quality = 2 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = -1, Quality = 1 }, new Item { Name = "Aged Brie", SellIn = -2, Quality = 3 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = -1, Quality = 49 }, new Item { Name = "Aged Brie", SellIn = -2, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = -1, Quality = 50 }, new Item { Name = "Aged Brie", SellIn = -2, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = -1, Quality = 51 }, new Item { Name = "Aged Brie", SellIn = -2, Quality = 51 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 0, Quality = -1 }, new Item { Name = "Aged Brie", SellIn = -1, Quality = 1 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 0, Quality = 0 }, new Item { Name = "Aged Brie", SellIn = -1, Quality = 2 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 0, Quality = 1 }, new Item { Name = "Aged Brie", SellIn = -1, Quality = 3 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 0, Quality = 49 }, new Item { Name = "Aged Brie", SellIn = -1, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 0, Quality = 50 }, new Item { Name = "Aged Brie", SellIn = -1, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 0, Quality = 51 }, new Item { Name = "Aged Brie", SellIn = -1, Quality = 51 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 1, Quality = -1 }, new Item { Name = "Aged Brie", SellIn = 0, Quality = 0 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 1, Quality = 0 }, new Item { Name = "Aged Brie", SellIn = 0, Quality = 1 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 1, Quality = 1 }, new Item { Name = "Aged Brie", SellIn = 0, Quality = 2 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 1, Quality = 49 }, new Item { Name = "Aged Brie", SellIn = 0, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 1, Quality = 50 }, new Item { Name = "Aged Brie", SellIn = 0, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 1, Quality = 51 }, new Item { Name = "Aged Brie", SellIn = 0, Quality = 51 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 5, Quality = -1 }, new Item { Name = "Aged Brie", SellIn = 4, Quality = 0 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 5, Quality = 0 }, new Item { Name = "Aged Brie", SellIn = 4, Quality = 1 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 5, Quality = 1 }, new Item { Name = "Aged Brie", SellIn = 4, Quality = 2 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 5, Quality = 49 }, new Item { Name = "Aged Brie", SellIn = 4, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 5, Quality = 50 }, new Item { Name = "Aged Brie", SellIn = 4, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 5, Quality = 51 }, new Item { Name = "Aged Brie", SellIn = 4, Quality = 51 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 6, Quality = -1 }, new Item { Name = "Aged Brie", SellIn = 5, Quality = 0 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 6, Quality = 0 }, new Item { Name = "Aged Brie", SellIn = 5, Quality = 1 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 6, Quality = 1 }, new Item { Name = "Aged Brie", SellIn = 5, Quality = 2 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 6, Quality = 49 }, new Item { Name = "Aged Brie", SellIn = 5, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 6, Quality = 50 }, new Item { Name = "Aged Brie", SellIn = 5, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 6, Quality = 51 }, new Item { Name = "Aged Brie", SellIn = 5, Quality = 51 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 7, Quality = -1 }, new Item { Name = "Aged Brie", SellIn = 6, Quality = 0 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 7, Quality = 0 }, new Item { Name = "Aged Brie", SellIn = 6, Quality = 1 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 7, Quality = 1 }, new Item { Name = "Aged Brie", SellIn = 6, Quality = 2 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 7, Quality = 49 }, new Item { Name = "Aged Brie", SellIn = 6, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 7, Quality = 50 }, new Item { Name = "Aged Brie", SellIn = 6, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 7, Quality = 51 }, new Item { Name = "Aged Brie", SellIn = 6, Quality = 51 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 10, Quality = -1 }, new Item { Name = "Aged Brie", SellIn = 9, Quality = 0 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 10, Quality = 0 }, new Item { Name = "Aged Brie", SellIn = 9, Quality = 1 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 10, Quality = 1 }, new Item { Name = "Aged Brie", SellIn = 9, Quality = 2 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 10, Quality = 49 }, new Item { Name = "Aged Brie", SellIn = 9, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 10, Quality = 50 }, new Item { Name = "Aged Brie", SellIn = 9, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 10, Quality = 51 }, new Item { Name = "Aged Brie", SellIn = 9, Quality = 51 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 11, Quality = -1 }, new Item { Name = "Aged Brie", SellIn = 10, Quality = 0 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 11, Quality = 0 }, new Item { Name = "Aged Brie", SellIn = 10, Quality = 1 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 11, Quality = 1 }, new Item { Name = "Aged Brie", SellIn = 10, Quality = 2 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 11, Quality = 49 }, new Item { Name = "Aged Brie", SellIn = 10, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 11, Quality = 50 }, new Item { Name = "Aged Brie", SellIn = 10, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 11, Quality = 51 }, new Item { Name = "Aged Brie", SellIn = 10, Quality = 51 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 12, Quality = -1 }, new Item { Name = "Aged Brie", SellIn = 11, Quality = 0 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 12, Quality = 0 }, new Item { Name = "Aged Brie", SellIn = 11, Quality = 1 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 12, Quality = 1 }, new Item { Name = "Aged Brie", SellIn = 11, Quality = 2 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 12, Quality = 49 }, new Item { Name = "Aged Brie", SellIn = 11, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 12, Quality = 50 }, new Item { Name = "Aged Brie", SellIn = 11, Quality = 50 } },
                new object[] { new Item { Name = "Aged Brie", SellIn = 12, Quality = 51 }, new Item { Name = "Aged Brie", SellIn = 11, Quality = 51 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = -1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -2, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 0 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -2, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -2, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 49 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -2, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 50 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -2, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 51 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -2, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = -1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 0 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 49 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 50 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 51 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = -1, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 1, Quality = -1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 2 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 1, Quality = 0 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 3 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 1, Quality = 1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 4 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 1, Quality = 49 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 1, Quality = 50 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 1, Quality = 51 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 0, Quality = 51 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = -1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 4, Quality = 2 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 0 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 4, Quality = 3 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 4, Quality = 4 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 49 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 4, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 50 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 4, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 51 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 4, Quality = 51 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = -1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 1 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 0 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 2 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 3 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 49 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 50 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 51 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 5, Quality = 51 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 7, Quality = -1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 1 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 7, Quality = 0 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 2 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 7, Quality = 1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 3 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 7, Quality = 49 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 7, Quality = 50 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 7, Quality = 51 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 6, Quality = 51 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = -1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 9, Quality = 1 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 0 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 9, Quality = 2 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 9, Quality = 3 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 49 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 9, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 50 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 9, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 51 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 9, Quality = 51 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = -1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 0 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 1 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 2 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 49 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 50 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 51 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 10, Quality = 51 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 12, Quality = -1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 0 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 12, Quality = 0 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 1 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 12, Quality = 1 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 2 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 12, Quality = 49 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 12, Quality = 50 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 50 } },
                new object[] { new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 12, Quality = 51 }, new Item { Name = "Backstage passes to a TAFKAL80ETC concert", SellIn = 11, Quality = 51 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = -1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = -1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = 0 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = 0 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = 1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = 1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = 49 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = 49 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = 50 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = 50 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = 51 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = -1, Quality = 51 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = -1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = -1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = 0 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = 0 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = 1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = 1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = 49 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = 49 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = 50 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = 50 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = 51 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 0, Quality = 51 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = -1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = -1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = 0 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = 0 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = 1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = 1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = 49 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = 49 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = 50 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = 50 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = 51 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 1, Quality = 51 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = -1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = -1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = 0 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = 0 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = 1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = 1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = 49 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = 49 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = 50 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = 50 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = 51 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 5, Quality = 51 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = -1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = -1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = 0 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = 0 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = 1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = 1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = 49 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = 49 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = 50 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = 50 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = 51 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 6, Quality = 51 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = -1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = -1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = 0 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = 0 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = 1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = 1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = 49 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = 49 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = 50 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = 50 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = 51 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 7, Quality = 51 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = -1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = -1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = 0 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = 0 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = 1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = 1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = 49 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = 49 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = 50 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = 50 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = 51 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 10, Quality = 51 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = -1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = -1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = 0 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = 0 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = 1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = 1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = 49 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = 49 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = 50 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = 50 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = 51 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 11, Quality = 51 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = -1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = -1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = 0 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = 0 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = 1 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = 1 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = 49 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = 49 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = 50 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = 50 } },
                new object[] { new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = 51 }, new Item { Name = "Sulfuras, Hand of Ragnaros", SellIn = 12, Quality = 51 } }
            };
        }
    }
}
